-- Seed Activities 96-144 months (8-12 years), ES + EN

INSERT INTO activities (emoji, title, subtitle, schema_target, domain, materials, duration_minutes, steps, science_note, age_min_months, age_max_months, language, is_featured)
VALUES
-- 96-108 ES
('🧪','Proyecto de investigación personal','Porque profundizar en lo que le apasiona construye motivación de largo plazo','none','Motivación',ARRAY['Libreta o carpeta','Libros o internet supervisado','Materiales del tema'],60,'1. Elegir una pregunta específica.\n2. Buscar información confiable juntos.\n3. Registrar hallazgos y dudas.\n4. Preparar mini presentación familiar.','El interés autodirigido fortalece perseverancia, autorregulación y sentido de competencia.',96,108,'es',true),
('⚖️','Debate en familia','Porque argumentar con evidencia fortalece pensamiento crítico','none','Cognitivo',ARRAY['Tema debatible','Papel','Cronómetro'],25,'1. Escoger tema con dos posturas.\n2. Preparar tres argumentos por persona.\n3. Exponer y contraargumentar.\n4. Cerrar con reflexión.','Debatir una postura ejercita flexibilidad cognitiva, lógica y comunicación.',96,108,'es',false),
('🗺️','Planificador de aventura','Porque planear un paseo real entrena funciones ejecutivas','none','Ejecutivo',ARRAY['Mapa','Papel','Presupuesto pequeño'],30,'1. Definir restricciones reales.\n2. Comparar opciones.\n3. Diseñar plan logístico.\n4. Revisar qué funcionó y qué cambiar.','Planificar con restricciones reales desarrolla metacognición y autoeficacia.',96,108,'es',false),

-- 96-108 EN
('🧪','Personal Research Project','Because going deep on what they love builds lifelong motivation','none','Motivation',ARRAY['Notebook','Books or supervised internet','Topic materials'],60,'1. Pick one specific question.\n2. Research from reliable sources.\n3. Capture findings and new questions.\n4. Share a short family presentation.','Self-directed interest supports persistence, self-regulation, and competence.',96,108,'en',true),
('⚖️','Family Debate','Because evidence-based argument builds critical thinking','none','Cognitive',ARRAY['Debate topic','Paper','Timer'],25,'1. Choose a two-sided topic.\n2. Prepare three arguments each.\n3. Present and counter-argue.\n4. Reflect on strongest evidence.','Debate practices cognitive flexibility, logic, and communication.',96,108,'en',false),
('🗺️','Adventure Planner','Because planning a real outing trains executive function','none','Executive',ARRAY['Map','Paper','Small budget'],30,'1. Set real constraints.\n2. Compare alternatives.\n3. Build the route and checklist.\n4. Debrief after the outing.','Real planning strengthens metacognition and self-efficacy.',96,108,'en',false),

-- 108-120 ES
('📰','Detective de noticias','Porque cuestionar información es una habilidad clave','none','Pensamiento crítico',ARRAY['Artículo apropiado','Papel de notas'],25,'1. Leer noticia juntos.\n2. Separar hechos de opiniones.\n3. Revisar segunda fuente.\n4. Escribir resumen propio.','La alfabetización mediática temprana mejora criterio y evaluación de fuentes.',108,120,'es',true),
('🍽️','Chef de la semana','Porque planear y cocinar integra matemáticas y autonomía','none','Autonomía',ARRAY['Receta','Lista de compras','Ingredientes'],60,'1. Elegir receta y presupuesto.\n2. Comprar con lista.\n3. Cocinar con supervisión.\n4. Evaluar proceso final.','Proyectos reales de cocina combinan lectura funcional, matemáticas y planificación.',108,120,'es',false),
('🎧','Curador musical en casa','Porque explicar por qué te gusta algo desarrolla identidad','none','Identidad',ARRAY['Lista de canciones','Cuaderno'],30,'1. Crear mini playlist temática.\n2. Explicar por qué eligió cada canción.\n3. Compartir sesión familiar.','Argumentar gustos musicales fortalece lenguaje reflexivo e identidad narrativa.',108,120,'es',false),

-- 108-120 EN
('📰','News Detective','Because questioning information is a core modern skill','none','Critical Thinking',ARRAY['Age-appropriate article','Notes paper'],25,'1. Read a news item together.\n2. Separate facts from opinions.\n3. Compare with a second source.\n4. Write a short own summary.','Early media literacy improves source evaluation and reasoning quality.',108,120,'en',true),
('🍽️','Chef of the Week','Because planning and cooking blends math with autonomy','none','Autonomy',ARRAY['Recipe','Shopping list','Ingredients'],60,'1. Choose recipe and budget.\n2. Shop from list.\n3. Cook with supervision.\n4. Reflect on outcomes.','Real cooking projects combine functional reading, math, and planning.',108,120,'en',false),
('🎧','Home Music Curator','Because explaining taste supports identity development','none','Identity',ARRAY['Song list','Notebook'],30,'1. Build a small themed playlist.\n2. Explain why each song was chosen.\n3. Share with family.','Explaining preferences strengthens reflective language and identity narrative.',108,120,'en',false),

-- 120-132 ES
('💡','Inventor por un día','Porque resolver un problema real es ingeniería aplicada','connecting','Ingeniería',ARRAY['Material reciclado','Cinta','Tijeras','Libreta'],45,'1. Elegir problema real en casa.\n2. Diseñar en papel.\n3. Construir prototipo.\n4. Probar, iterar y presentar.','El ciclo diseño-prototipo-prueba entrena pensamiento ingenieril y adaptación.',120,132,'es',true),
('📝','Mi manifiesto personal','Porque poner valores en palabras clarifica identidad','none','Identidad',ARRAY['Libreta','Marcadores'],30,'1. Responder preguntas guía sobre valores.\n2. Escribir frases "Yo soy/creo/quiero".\n3. Guardar para revisión futura.','La auto-reflexión guiada fortalece construcción de identidad y agencia.',120,132,'es',false),
('🌱','Mentor de hermano menor','Porque enseñar consolida aprendizaje y empatía','none','Social',ARRAY['Actividad simple a enseñar','Material básico'],30,'1. Elegir algo que pueda enseñar.\n2. Planear explicación paso a paso.\n3. Enseñar con paciencia.\n4. Reflexionar qué funcionó.','El efecto protégé: enseñar mejora comprensión y empatía.',120,132,'es',false),

-- 120-132 EN
('💡','Inventor for a Day','Because solving a real problem is applied engineering','connecting','Engineering',ARRAY['Recycled materials','Tape','Scissors','Notebook'],45,'1. Pick a real household problem.\n2. Sketch solution.\n3. Build a prototype.\n4. Test, iterate, present.','Design cycles train engineering thinking and adaptive problem solving.',120,132,'en',true),
('📝','My Personal Manifesto','Because writing values clarifies identity and direction','none','Identity',ARRAY['Notebook','Markers'],30,'1. Answer guided value prompts.\n2. Write "I am/I believe/I want" statements.\n3. Store for future revisit.','Guided reflection supports identity construction and personal agency.',120,132,'en',false),
('🌱','Younger-Sibling Mentor','Because teaching consolidates learning and empathy','none','Social',ARRAY['Simple topic to teach','Basic materials'],30,'1. Pick one thing to teach.\n2. Plan steps.\n3. Teach patiently.\n4. Reflect on what worked.','The protégé effect: teaching deepens understanding and empathy.',120,132,'en',false),

-- 132-144 ES
('🧭','Mapa de vida: 3 futuros posibles','Porque imaginar varios futuros reduce la presión de "elegir bien"','none','Identidad',ARRAY['3 hojas grandes','Marcadores','Revistas opcionales'],40,'1. Dibujar tres futuros posibles.\n2. Describir un día típico en cada uno.\n3. Comparar patrones comunes.','Explorar múltiples futuros disminuye ansiedad y fortalece claridad de valores.',132,144,'es',true),
('🎤','TED Talk en casa','Porque enseñar un tema propio consolida aprendizaje','none','Comunicación',ARRAY['Tema favorito','Notas','Teléfono opcional'],30,'1. Preparar charla de 5 minutos.\n2. Practicar apertura y cierre.\n3. Presentar y responder preguntas.','Presentar desarrolla organización mental, comunicación oral y confianza.',132,144,'es',false),
('🤝','Proyecto de impacto','Porque ayudar a otros construye propósito','none','Propósito',ARRAY['Depende del proyecto','Plan de acción'],60,'1. Elegir problema comunitario.\n2. Planificar acciones y recursos.\n3. Ejecutar con liderazgo del niño/a.\n4. Documentar impacto.','Actividades con impacto social aumentan motivación por significancia.',132,144,'es',false),

-- 132-144 EN
('🧭','Life Map: 3 Possible Futures','Because imagining multiple futures reduces pressure to choose perfectly','none','Identity',ARRAY['3 large sheets','Markers','Optional magazines'],40,'1. Draw three possible futures.\n2. Describe a typical day in each.\n3. Compare common patterns.','Exploring multiple futures reduces anxiety and clarifies values.',132,144,'en',true),
('🎤','Home TED Talk','Because teaching a passion topic consolidates learning','none','Communication',ARRAY['Passion topic','Notes','Optional phone'],30,'1. Prepare a 5-minute talk.\n2. Practice opening and close.\n3. Present and answer questions.','Presenting develops information structure, oral communication, and confidence.',132,144,'en',false),
('🤝','Impact Project','Because contributing to others builds purpose','none','Purpose',ARRAY['Project-specific materials','Action plan'],60,'1. Choose a community issue.\n2. Plan tasks and resources.\n3. Execute with child leadership.\n4. Document outcomes.','Social impact work strengthens significance-driven motivation.',132,144,'en',false)
ON CONFLICT DO NOTHING;
