alter table public.explore_articles
  add column if not exists content jsonb,
  add column if not exists sources text;

update public.explore_articles
set content = jsonb_build_object(
  'sections', jsonb_build_array(jsonb_build_object('type', 'body', 'text', body)),
  'sources', coalesce(sources, 'Erikson · Gerber/RIE · Harvard CCHD · Diamond')
)
where content is null;

update public.explore_articles
set sources = coalesce(sources, content->>'sources', 'Erikson · Gerber/RIE · Harvard CCHD · Diamond')
where sources is null;

with articles as (
  select * from (values
    (
      '✊', 'Por qué el “no” es una gran noticia para {childName}', 'research', 'Autonomía', 5, 12, 24,
      'Cada “no” está construyendo identidad y autocontrol.',
      '{"sections":[{"type":"body","text":"Cuando {childName} dice no, su cerebro está practicando agencia, no rebeldía."},{"type":"pull_quote","emoji":"💡","text":"Cada \"no\" es una declaración de identidad: \"yo también tengo voz\"."},{"type":"section_header","text":"La ciencia detrás"},{"type":"science_callout","title":"Erikson + funciones ejecutivas","text":"Entre 12 y 24 meses, afirmar preferencias fortalece autonomía, base de la autorregulación futura."},{"type":"numbered_insight","number":1,"title":"Valida antes de redirigir","text":"\"Escucho tu no\" baja tensión y abre cooperación."},{"type":"numbered_insight","number":2,"title":"Ofrece dos opciones","text":"Da control dentro de límites seguros."},{"type":"try_this","text":"Hoy, cuando diga no, pausa 5 segundos y ofrece dos caminos concretos."},{"type":"warm_tip","emoji":"💛","text":"Tu calma le enseña que puede disentir sin perder conexión."}],"sources":"Erikson · Gerber/RIE · Diamond"}'
    ),
    ('🧺','Transportar tesoros: por qué {childName} mueve todo por la casa','article','Play schemas',4,12,24,'Transportar objetos es pensamiento científico en acción.','{"sections":[{"type":"body","text":"Si {childName} llena y vacía bolsas, no está desordenando: está estudiando peso, volumen y propósito."},{"type":"section_header","text":"Qué está descubriendo"},{"type":"body","text":"El schema de transporting conecta memoria de trabajo, planificación y causa-efecto."},{"type":"try_this","text":"Deja una cesta con objetos seguros de distintos tamaños y observa su lógica."},{"type":"warm_tip","emoji":"🌟","text":"Tu observación atenta convierte caos aparente en aprendizaje visible."}],"sources":"Athey Play Schemas · Piaget"}'),
    ('🌀','La fascinación por girar: cerebro en modo laboratorio','research','Sensorimotor',4,12,24,'Girar, repetir y mirar fortalece predicción y atención.','{"sections":[{"type":"body","text":"Cuando {childName} gira tapas o ruedas, está buscando patrones estables en un mundo cambiante."},{"type":"science_callout","title":"Predicción y curiosidad","text":"El marco PACE explica cómo pequeñas sorpresas disparan exploración y aprendizaje."},{"type":"try_this","text":"Ofrece coladores, tapas y ruedas de juguete para comparar giros rápidos y lentos."}],"sources":"PACE Framework · Piaget"}'),
    ('📦','Dentro y fuera: el poder del schema de enclosure','guide','Cognitivo',4,12,24,'Meter y sacar objetos construye lógica espacial.','{"sections":[{"type":"body","text":"{childName} aprende que los objetos pueden contener y ser contenidos: base del pensamiento matemático temprano."},{"type":"numbered_insight","number":1,"title":"Recipientes variados","text":"Cajas, tazas y bowls cambian la dificultad."},{"type":"numbered_insight","number":2,"title":"Nombra relaciones","text":"\"Dentro\", \"fuera\", \"lleno\", \"vacío\" enriquecen lenguaje."},{"type":"warm_tip","text":"No necesitas juguetes caros: cocina y reciclaje alcanzan."}],"sources":"Athey · Vygotsky"}'),
    ('🧠','Rabietas y cerebro inmaduro: una lectura compasiva','research','Socioemocional',6,14,24,'La desregulación no es manipulación: es desarrollo en curso.','{"sections":[{"type":"body","text":"Cuando {childName} explota, su sistema de freno aún está madurando."},{"type":"pull_quote","emoji":"🤲","text":"La co-regulación hoy se vuelve autorregulación mañana."},{"type":"science_callout","title":"Funciones ejecutivas","text":"Inhibición y flexibilidad cognitiva crecen con apoyo sensible repetido."},{"type":"try_this","text":"Habla poco, respira lento y ofrece contención física si la acepta."}],"sources":"Diamond · Harvard CCHD"}'),
    ('🗣️','Primeras palabras, gran revolución mental','article','Lenguaje',5,12,24,'Comprende mucho más de lo que puede decir.','{"sections":[{"type":"body","text":"{childName} está construyendo un diccionario interno enorme antes de hablar fluido."},{"type":"numbered_insight","number":1,"title":"Turnos conversacionales","text":"Pausa para que responda con gesto, sonido o mirada."},{"type":"numbered_insight","number":2,"title":"Nombra lo que le interesa","text":"El vocabulario pega mejor cuando nace de su foco."},{"type":"warm_tip","emoji":"💬","text":"Tu voz cálida es herramienta de neurodesarrollo."}],"sources":"Harvard CCHD · Hidi & Renninger"}'),
    ('🫧','Repetición infinita: por qué hacer lo mismo sí importa','guide','Aprendizaje',4,12,24,'Repetir consolida redes neuronales y confianza.','{"sections":[{"type":"body","text":"Cuando {childName} repite una acción, está afinando precisión y predicción."},{"type":"science_callout","title":"Práctica + cerebro","text":"La repetición con pequeñas variaciones acelera automatización y flexibilidad."},{"type":"try_this","text":"Permite 10 repeticiones antes de proponer algo nuevo."}],"sources":"Piaget · Diamond"}'),
    ('🤝','Serve & Return en la vida real: micro-momentos que transforman','guide','Vínculo',5,12,24,'Responder a sus señales fortalece lenguaje y apego seguro.','{"sections":[{"type":"section_header","text":"El ciclo de 5 pasos"},{"type":"numbered_insight","number":1,"title":"Observa la señal","text":"Mirada, gesto, sonido o movimiento."},{"type":"numbered_insight","number":2,"title":"Responde con calidez","text":"Sigue su foco antes de dirigir."},{"type":"numbered_insight","number":3,"title":"Espera su vuelta","text":"La pausa crea conversación."},{"type":"warm_tip","text":"Tu presencia atenta es ciencia aplicada."}],"sources":"Harvard CCHD Serve & Return"}'),
    ('🎯','Autonomía sin caos: límites que sí funcionan','guide','Autonomía',5,12,24,'Límites claros + elección reducen luchas de poder.','{"sections":[{"type":"body","text":"{childName} necesita estructura para sentirse seguro y opciones para sentirse capaz."},{"type":"numbered_insight","number":1,"title":"Una regla, dos opciones","text":"\"Es hora de salir: ¿zapatos rojos o azules?\""},{"type":"numbered_insight","number":2,"title":"Anticipa transiciones","text":"Avisos breves previenen choques."},{"type":"warm_tip","emoji":"🌈","text":"Firmeza amable es la combinación ganadora."}],"sources":"Self-Determination Theory · RIE"}'),
    ('🧩','Conectar y desconectar: ingeniería temprana','article','Play schemas',4,12,24,'Unir piezas entrena pensamiento causal.','{"sections":[{"type":"body","text":"Cuando {childName} conecta bloques, cintas o tapas, está modelando sistemas."},{"type":"science_callout","title":"ZPD","text":"Con una pista mínima, puede resolver retos más complejos."},{"type":"try_this","text":"Prepara materiales que encajen de varias formas y describe su estrategia."}],"sources":"Vygotsky · Athey"}')
  ) as t(emoji,title,type,domain,read_time_minutes,age_min_months,age_max_months,summary,content)
)
insert into public.explore_articles (emoji,title,type,domain,summary,body,read_time_minutes,age_min_months,age_max_months,language,content,sources)
select a.emoji,a.title,a.type,a.domain,a.summary,a.summary,a.read_time_minutes,a.age_min_months,a.age_max_months,'es',a.content::jsonb, (a.content::jsonb->>'sources')
from articles a
where not exists (
  select 1 from public.explore_articles e where lower(e.title)=lower(a.title) and e.language='es'
);
